# Generated by Django 3.1.2 on 2020-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201111_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='atcive',
            field=models.BooleanField(default='True'),
        ),
    ]
