# Generated by Django 3.1.2 on 2020-11-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_atcive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='atcive',
            new_name='active',
        ),
    ]
